_wandb:
    value:
        cli_version: 0.21.0
        e:
            pyxqpkm6znlyn5b2i79h08xn11hl0vjj:
                args:
                    - --resume
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "511304527872"
                        used: "302039535616"
                email: qdao.cntt@gmail.com
                executable: C:\Users\daotq\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: fc9278a56cbe880a2c698eb5d1e72e6251e47e45
                    remote: https://github.com/tqdaoinfo108/Vehicle-Detection.git
                host: DESKTOP-TNF68JI
                memory:
                    total: "42718257152"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\daotq\Documents\Source_daotq\Git\Vehicle-Detection\train.py
                python: CPython 3.11.8
                root: C:\Users\daotq\Documents\Source_daotq\Git\Vehicle-Detection
                startedAt: "2025-07-30T03:07:08.931791Z"
                writerId: pyxqpkm6znlyn5b2i79h08xn11hl0vjj
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
                - 80
            "3":
                - 5
                - 14
                - 16
                - 62
            "4": 3.11.8
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
adam:
    value: false
artifact_alias:
    value: latest
batch_size:
    value: 16
bbox_interval:
    value: -1
bucket:
    value: ""
cache:
    value: null
cfg:
    value: ""
data:
    value: dataset.yaml
data_dict:
    value:
        names:
            - Car
            - Motorcycle
            - Truck
            - Bus
            - Bicycle
        nc: 5
        path: Dataset/dataset-vehicles
        test: null
        train: Dataset\dataset-vehicles\images\train
        val: Dataset\dataset-vehicles\images\val
device:
    value: ""
entity:
    value: null
epochs:
    value: 50
evolve:
    value: null
exist_ok:
    value: false
freeze:
    value: 0
hyp:
    value:
        anchor_t: 4
        box: 0.05
        cls: 0.5
        cls_pw: 1
        copy_paste: 0
        degrees: 0
        fl_gamma: 0
        fliplr: 0.5
        flipud: 0
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        iou_t: 0.2
        lr0: 0.01
        lrf: 0.2
        mixup: 0
        momentum: 0.937
        mosaic: 1
        obj: 1
        obj_pw: 1
        perspective: 0
        scale: 0.5
        shear: 0
        translate: 0.1
        warmup_bias_lr: 0.1
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
image_weights:
    value: false
imgsz:
    value: 640
label_smoothing:
    value: 0
linear_lr:
    value: false
local_rank:
    value: -1
multi_scale:
    value: false
name:
    value: exp
noautoanchor:
    value: false
nosave:
    value: false
noval:
    value: false
patience:
    value: 30
project:
    value: runs/train
quad:
    value: false
rect:
    value: false
resume:
    value: true
save_dir:
    value: runs\train\exp17
save_period:
    value: -1
single_cls:
    value: false
sync_bn:
    value: false
upload_dataset:
    value: false
weights:
    value: .\runs\train\exp17\weights\last.pt
workers:
    value: 8
